[package]
name = "tenant"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12.15", features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
serde = { version = "1.0.203", features = ["derive"] }
anyhow = "1.0.86"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros", "time", "signal"] }
lazy_static = "1.4.0"
regex = "1.10.5"
