create table if not exists voucher_type
(
    id          int               not null GENERATED BY default as identity (start with 101 increment by 1) primary key,
    name        text              not null,
    prefix      text,
    sequence_id int     references voucher_type,
    is_default  boolean           not null default false,
    base_type   text              not null,
    config      json              not null,
    approve1_id int,
    approve2_id int,
    approve3_id int,
    approve4_id int,
    approve5_id int,
    members     jsonb,
    created_at  timestamp         not null default current_timestamp,
    updated_at  timestamp         not null default current_timestamp,
    constraint name_min_length check (char_length(trim(name)) > 0),
    constraint prefix_invalid check (prefix ~ '^[A-Z]+$' and char_length(prefix) between 2 and 3),
    constraint base_type_invalid check (check_base_voucher_type(base_type))
);
--##
create trigger sync_voucher_type_updated_at
    before update
    on voucher_type
    for each row
execute procedure sync_updated_at();