insert into account_type (id, default_name, name, parent_id, allow_account, allow_sub_type,
                          base_types) overriding system value
values (1, 'CURRENT_ASSET', 'Current Asset', null, true, true, array ['CURRENT_ASSET']),
       (2, 'CURRENT_LIABILITY', 'Current Liability', null, true, true, array ['CURRENT_LIABILITY']),
       (3, 'DIRECT_INCOME', 'Direct Income', null, true, true, array ['DIRECT_INCOME']),
       (4, 'INDIRECT_INCOME', 'Indirect Income', null, true, true, array ['INDIRECT_INCOME']),
       (5, 'SALE', 'Sale', null, false, false, array ['SALE']),
       (6, 'DIRECT_EXPENSE', 'Direct Expense', null, true, true, array ['DIRECT_INCOME']),
       (7, 'INDIRECT_EXPENSE', 'Indirect Expense', null, true, true, array ['INDIRECT_EXPENSE']),
       (8, 'PURCHASE', 'Purchase', null, false, false, array ['PURCHASE']),
       (9, 'FIXED_ASSET', 'Fixed Asset', null, true, true, array ['FIXED_ASSET']),
       (10, 'LONGTERM_LIABILITY', 'Longterm Liability', null, true, true, array ['LONGTERM_LIABILITY']),
       (11, 'EQUITY', 'Equity', null, true, true, array ['EQUITY']),
       (12, 'STOCK', 'Stock', null, false, false, array ['STOCK']),
       (13, 'BANK_ACCOUNT', 'Bank Account', 1, true, false, array ['CURRENT_ASSET', 'BANK_ACCOUNT']),
       (14, 'EFT_ACCOUNT', 'EFT Account', 1, true, false, array ['CURRENT_ASSET', 'EFT_ACCOUNT']),
       (15, 'TDS_RECEIVABLE', 'Tds Receivable', 1, true, false, array ['CURRENT_ASSET', 'TDS_RECEIVABLE']),
       (16, 'SUNDRY_DEBTOR', 'Sundry Debtors', 1, true, true, array ['CURRENT_ASSET', 'SUNDRY_DEBTOR']),
       (17, 'CASH', 'Cash', 1, true, true, array ['CURRENT_ASSET', 'CASH']),
       (18, 'BANK_OD_ACCOUNT', 'Bank OD Account', 2, true, false, array ['CURRENT_LIABILITY', 'BANK_OD_ACCOUNT']),
       (19, 'SUNDRY_CREDITOR', 'Sundry Creditor', 2, true, true, array ['CURRENT_LIABILITY', 'SUNDRY_CREDITOR']),
       (20, 'BRANCH_OR_DIVISION', 'Branch / Division', 2, true, false,
        array ['CURRENT_LIABILITY', 'BRANCH_OR_DIVISION']),
       (21, 'TDS_PAYABLE', 'Tds Payable', 2, true, false, array ['CURRENT_LIABILITY', 'TDS_PAYABLE']),
       (22, 'DUTIES_AND_TAXES', 'Duties And Taxes', 2, true, false, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']);
--##
insert into gst_tax
(id, name, cgst, sgst, igst) values
('gstna', 'Not Applicable', 0.0, 0.0, 0.0),
('gstexempt', 'GST Exempt', 0.0, 0.0, 0.0),
('gstngs', 'Non GST Supply', 0.0, 0.0, 0.0),
('gst0', 'GST 0%', 0.0, 0.0, 0.0),
('gst0p1', 'GST 0.1%', 0.05, 0.05, 0.1),
('gst0p25', 'GST 0.25%', 0.125, 0.125, 0.25),
('gst1', 'GST 1%', 0.5, 0.5, 1.0),
('gst1p5', 'GST 1.5%', 0.75, 0.75, 1.5),
('gst3', 'GST 3%', 1.5, 1.5, 3.0),
('gst5', 'GST 5%', 2.5, 2.5, 5.0),
('gst7p5', 'GST 7.5%', 3.75, 3.75, 7.5),
('gst12', 'GST 12%', 6.0, 6.0, 12.0),
('gst18', 'GST 18%', 9.0, 9.0, 18.0),
('gst28', 'GST 28%', 14.0, 14.0, 28.0);
--##
insert into account
(id,name,account_type_id,gst_type,is_default, base_account_types) overriding system value values
(1,'Cash',17, null,true, array ['CURRENT_ASSET', 'CASH']),
(2,'Sales',5,null,true, array ['SALE']),
(3,'Purchases',8,null,true, array ['PURCHASE']),
(4,'CGST Payable', 22,'CGST',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(5,'SGST Payable', 22,'SGST',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(6,'IGST Payable', 22,'IGST',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(7,'CESS Payable', 22,'CESS',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(8,'CGST Receivable', 22,'CGST',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(9,'SGST Receivable', 22,'SGST',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(10,'IGST Receivable', 22,'IGST',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(11,'CESS Receivable', 22,'CESS',true, array ['CURRENT_LIABILITY', 'DUTIES_AND_TAXES']),
(12,'Rounded Off',4,null,true, array ['INDIRECT_INCOME']),
(13,'Discount Given',7,null,true, array ['INDIRECT_EXPENSE']),
(14,'Discount Received',4,null,true, array ['INDIRECT_INCOME']),
(15,'Gift Voucher Reimbursement',2,null,true, array ['CURRENT_LIABILITY']),
(16,'Inventory Asset',12,null,true, array ['STOCK']),
(17, 'RCM Payable', 2, null, true, array ['CURRENT_LIABILITY']);
--##
insert into country
(id, name, country_id) values
('INDIA', 'India', null),
('01', 'Jammu And Kashmir', 'INDIA'),
('02', 'Himachal Pradesh', 'INDIA'),
('03', 'Punjab', 'INDIA'),
('04', 'Chandigarh', 'INDIA'),
('05', 'Uttarakhand', 'INDIA'),
('06', 'Haryana', 'INDIA'),
('07', 'Delhi', 'INDIA'),
('08', 'Rajasthan', 'INDIA'),
('09', 'Uttar Pradesh', 'INDIA'),
('10', 'Bihar', 'INDIA'),
('11', 'Sikkim', 'INDIA'),
('12', 'Arunachal Pradesh', 'INDIA'),
('13', 'Nagaland', 'INDIA'),
('14', 'Manipur', 'INDIA'),
('15', 'Mizoram', 'INDIA'),
('16', 'Tripura', 'INDIA'),
('17', 'Meghlaya', 'INDIA'),
('18', 'Assam', 'INDIA'),
('19', 'West Bengal', 'INDIA'),
('20', 'Jharkhand', 'INDIA'),
('21', 'Odisha', 'INDIA'),
('22', 'Chattisgarh', 'INDIA'),
('23', 'Madhya Pradesh', 'INDIA'),
('24', 'Gujarat', 'INDIA'),
('25', 'Daman And Diu', 'INDIA'),
('26', 'Dadra And Nagar Haveli', 'INDIA'),
('27', 'Maharashtra', 'INDIA'),
('28', 'Andhra Pradesh Old', 'INDIA'),
('29', 'Karnataka', 'INDIA'),
('30', 'Goa', 'INDIA'),
('31', 'Lakshwadeep', 'INDIA'),
('32', 'Kerala', 'INDIA'),
('33', 'TamilNadu', 'INDIA'),
('34', 'Puducherry', 'INDIA'),
('35', 'Andaman and Nicobar Islands', 'INDIA'),
('36', 'Telangana', 'INDIA'),
('37', 'Andhra Pradesh New', 'INDIA');
--##
insert into tds_deductee_type
(id, name) values
('ARTIFICIAL_JURIDICAL_PERSON','Artificial Juridical Person'),
('ASSOCIATION_OF_PERSONS','Association of Persons'),
('BODY_OF_INDIVIDUALS','Body of Individuals'),
('COMPANY_NON_RESIDENT','Company - Non Resident'),
('COMPANY_RESIDENT','Company - Resident'),
('CO_OPERATIVE_SOCIETY_NON_RESIDENT','Co-Operative Society - Non Resident'),
('CO_OPERATIVE_SOCIETY_RESIDENT','Co-Operative Society - Resident'),
('GOVERNMENT','Government'),
('INDIVIDUAL_HUF_NON_RESIDENT','Individual/HUF - Non Resident'),
('INDIVIDUAL_HUF_RESIDENT','Individual/HUF - Resident'),
('LOCAL_AUTHORITY','Local Authority'),
('PARTNERSHIP_FIRM','Partnership Firm');
--##
insert into uqc
(id,name) values
 ('BAG', 'BAG-BAGS'),
 ('BAL', 'BAL-BALE'),
 ('BDL', 'BDL-BUNDLES'),
 ('BKL', 'BKL-BUCKLES'),
 ('BOU', 'BOU-BILLION OF UNITS'),
 ('BOX', 'BOX-BOX'),
 ('BTL', 'BTL-BOTTLES'),
 ('BUN', 'BUN-BUNCHES'),
 ('CAN', 'CAN-CANS'),
 ('CBM', 'CBM-CUBIC METERS'),
 ('CCM', 'CCM-CUBIC CENTIMETERS'),
 ('CMS', 'CMS-CENTIMETERS'),
 ('CTN', 'CTN-CARTONS'),
 ('DOZ', 'DOZ-DOZENS'),
 ('DRM', 'DRM-DRUMS'),
 ('GGK', 'GGK-GREAT GROSS'),
 ('GMS', 'GMS-GRAMMES'),
 ('GRS', 'GRS-GROSS'),
 ('GYD', 'GYD-GROSS YARDS'),
 ('KGS', 'KGS-KILOGRAMS'),
 ('KLR', 'KLR-KILOLITRE'),
 ('KME', 'KME-KILOMETRE'),
 ('LTR', 'LTR-LITRES'),
 ('MLT', 'MLT-MILILITRE'),
 ('MTR', 'MTR-METERS'),
 ('MTS', 'MTS-METRIC TON'),
 ('NOS', 'NOS-NUMBERS'),
 ('PAC', 'PAC-PACKS'),
 ('PCS', 'PCS-PIECES'),
 ('PRS', 'PRS-PAIRS'),
 ('QTL', 'QTL-QUINTAL'),
 ('ROL', 'ROL-ROLLS'),
 ('SET', 'SET-SETS'),
 ('SQF', 'SQF-SQUARE FEET'),
 ('SQM', 'SQM-SQUARE METERS'),
 ('SQY', 'SQY-SQUARE YARDS'),
 ('TBS', 'TBS-TABLETS'),
 ('TGM', 'TGM-TEN GROSS'),
 ('THD', 'THD-THOUSANDS'),
 ('TON', 'TON-TONNES'),
 ('TUB', 'TUB-TUBES'),
 ('UGS', 'UGS-US GALLONS'),
 ('UNT', 'UNT-UNITS'),
 ('YDS', 'YDS-YARDS'),
 ('OTH', 'OTH-OTHERS');
--##
insert into category
(id, name, sort_order, sno, category_type) values
('INV_CAT1','Category 1',1,1,'INVENTORY'),
('INV_CAT2','Category 2',2,2,'INVENTORY'),
('INV_CAT3','Category 3',3,3,'INVENTORY'),
('INV_CAT4','Category 4',4,4,'INVENTORY'),
('INV_CAT5','Category 5',5,5,'INVENTORY'),
('INV_CAT6','Category 6',6,6,'INVENTORY'),
('INV_CAT7','Category 7',7,7,'INVENTORY'),
('INV_CAT8','Category 8',8,8,'INVENTORY'),
('INV_CAT9','Category 9',9,9,'INVENTORY'),
('INV_CAT10','Category 10',10,10,'INVENTORY'),
('ACC_CAT1','Category 1',1,1,'ACCOUNT'),
('ACC_CAT2','Category 2',2,2,'ACCOUNT'),
('ACC_CAT3','Category 3',3,3,'ACCOUNT'),
('ACC_CAT4','Category 4',4,4,'ACCOUNT'),
('ACC_CAT5','Category 5',5,5,'ACCOUNT');
--##
-- insert into permission
-- (id,name,uri,req,tag) values
-- ('ac.actyp.vw','View Account Type','Accounting/Account Type/List',null,'View'),
-- ('ac.actyp.cr','Create Account Type','Accounting/Account Type/Create','{"ac.actyp.vw"}','Create'),
-- ('ac.actyp.up','Update Account Type','Accounting/Account Type/Update','{"ac.actyp.vw","ac.actyp.cr"}','Update'),
-- ('ac.actyp.dl','Delete Account Type','Accounting/Account Type/Delete','{"ac.actyp.vw","ac.actyp.cr","ac.actyp.up"}','Delete'),
-- ('ac.ac.vw','View Account','Accounting/Account/List',null,'View'),
-- ('ac.ac.cr','Create Account','Accounting/Account/Create','{"ac.ac.vw"}','Create'),
-- ('ac.ac.up','Update Account','Accounting/Account/Update','{"ac.ac.vw","ac.ac.cr"}','Update'),
-- ('ac.ac.dl','Delete Account','Accounting/Account/Delete','{"ac.ac.vw","ac.ac.cr","ac.ac.up"}','Delete'),
-- ('ac.ac.op','Account Opening','Accounting/Account/Opening','{"ac.ac.vw","ac.ac.cr"}','Options'),
-- ('ac.ctra.vw','View Contra','Accounting/Contra/View',null,'View'),
-- ('ac.ctra.cr','Create Contra','Accounting/Contra/Create','{"ac.ctra.vw"}','Create'),
-- ('ac.ctra.up','Update Contra','Accounting/Contra/Update','{"ac.ctra.vw","ac.ctra.cr"}','Update'),
-- ('ac.ctra.dl','Delete Contra','Accounting/Contra/Delete','{"ac.ctra.vw","ac.ctra.cr","ac.ctra.up"}','Delete'),
-- ('ac.ctra.cnl','Contra Cancel','Accounting/Contra/Cancel','{"ac.ctra.vw"}','Options'),
-- ('ac.jo.vw','View Journal','Accounting/Journal/View',null,'View'),
-- ('ac.jo.cr','Create Journal','Accounting/Journal/Create','{"ac.jo.vw"}','Create'),
-- ('ac.jo.up','Update Journal','Accounting/Journal/Update','{"ac.jo.vw","ac.jo.cr"}','Update'),
-- ('ac.jo.dl','Delete Journal','Accounting/Journal/Delete','{"ac.jo.vw","ac.jo.cr","ac.jo.up"}','Delete'),
-- ('ac.jo.cnl','Journal Cancel','Accounting/Journal/Cancel','{"ac.jo.vw"}','Options'),
-- ('ac.pmt.vw','View Payment','Accounting/Payment/View',null,'View'),
-- ('ac.pmt.cr','Create Payment','Accounting/Payment/Create','{"ac.pmt.vw","utly.chq.bk"}','Create'),
-- ('ac.pmt.up','Update Payment','Accounting/Payment/Update','{"ac.pmt.vw","ac.pmt.cr","utly.chq.bk"}','Update'),
-- ('ac.pmt.dl','Delete Payment','Accounting/Payment/Delete','{"ac.pmt.vw","ac.pmt.cr","ac.pmt.up","utly.chq.bk"}','Delete'),
-- ('ac.pmt.rvw','Review Payment','Accounting/Payment/Review','{"ac.pmt.vw"}','Options'),
-- ('ac.pmt.cnl','Payment Cancel','Accounting/Payment/Cancel','{"ac.pmt.vw"}','Options'),
-- ('ac.rcpt.vw','View Receipt','Accounting/Receipt/View',null,'View'),
-- ('ac.rcpt.cr','Create Receipt','Accounting/Receipt/Create','{"ac.rcpt.vw"}','Create'),
-- ('ac.rcpt.up','Update Receipt','Accounting/Receipt/Update','{"ac.rcpt.vw","ac.rcpt.cr"}','Update'),
-- ('ac.rcpt.dl','Delete Receipt','Accounting/Receipt/Delete','{"ac.rcpt.vw","ac.rcpt.cr","ac.rcpt.up"}','Delete'),
-- ('ac.rcpt.rvw','Review Receipt','Accounting/Receipt/Review','{"ac.rcpt.vw"}','Options'),
-- ('ac.rcpt.cnl','Receipt Cancel','Accounting/Receipt/Cancel','{"ac.rcpt.vw"}','Options'),
-- ('inv.inv.vw','View Inventory','Inventory/Inventory/List',null,'View'),
-- ('inv.inv.cr','Create Inventory','Inventory/Inventory/Create','{"inv.inv.vw"}','Create'),
-- ('inv.inv.up','Update Inventory','Inventory/Inventory/Update','{"inv.inv.vw","inv.inv.cr"}','Update'),
-- ('inv.inv.dl','Delete Inventory','Inventory/Inventory/Delete','{"inv.inv.vw","inv.inv.cr","inv.inv.up"}','Delete'),
-- ('inv.inv.mrg','Merge Inventory','Inventory/Inventory/Merge','{"inv.inv.vw"}','Merge'),
-- ('inv.inv.op','Inventory Opening','Inventory/Inventory/Opening','{"inv.inv.vw","inv.inv.cr"}','Options'),
-- ('inv.inv.asl','Assign Stock Location','Inventory/Inventory/AssignStockLocation','{"inv.inv.vw"}','Options'),
-- ('inv.inv.untcnv','Unit Conversion','Inventory/Inventory/UnitConversion','{"inv.inv.vw","inv.inv.cr"}','Options'),
-- ('inv.inv.pc','Price Configuration','Inventory/Inventory/PriceConfiguration','{"inv.inv.vw","inv.inv.cr"}','Options'),
-- ('inv.inv.dlr','Inventory Dealer','Inventory/Inventory/InventoryDealer','{"inv.inv.vw","inv.inv.cr"}','Options'),
-- ('inv.man.vw','View Manufacturer','Inventory/Manufacturer/List',null,'View'),
-- ('inv.man.cr','Create Manufacturer','Inventory/Manufacturer/Create','{"inv.man.vw"}','Create'),
-- ('inv.man.up','Update Manufacturer','Inventory/Manufacturer/Update','{"inv.man.vw","inv.man.cr"}','Update'),
-- ('inv.man.dl','Delete Manufacturer','Inventory/Manufacturer/Delete','{"inv.man.vw","inv.man.cr","inv.man.up"}','Delete'),
-- ('inv.war.vw','View Warehouse','Inventory/Warehouse/List',null,'View'),
-- ('inv.war.cr','Create Warehouse','Inventory/Warehouse/Create','{"inv.war.vw"}','Create'),
-- ('inv.war.up','Update Warehouse','Inventory/Warehouse/Update','{"inv.war.vw","inv.war.cr"}','Update'),
-- ('inv.war.dl','Delete Warehouse','Inventory/Warehouse/Delete','{"inv.war.vw","inv.war.cr","inv.war.up"}','Delete'),
-- ('inv.sinc.vw','View SaleIncharge','Inventory/SaleIncharge/List',null,'View'),
-- ('inv.sinc.cr','Create SaleIncharge','Inventory/SaleIncharge/Create','{"inv.sinc.vw"}','Create'),
-- ('inv.sinc.up','Update SaleIncharge','Inventory/SaleIncharge/Update','{"inv.sinc.vw","inv.sinc.cr"}','Update'),
-- ('inv.sinc.dl','Delete SaleIncharge','Inventory/SaleIncharge/Delete','{"inv.sinc.vw","inv.sinc.cr","inv.sinc.up"}','Delete'),
-- ('inv.unt.vw','View Unit','Inventory/Unit/List',null,'View'),
-- ('inv.unt.cr','Create Unit','Inventory/Unit/Create','{"inv.unt.vw"}','Create'),
-- ('inv.unt.up','Update Unit','Inventory/Unit/Update','{"inv.unt.vw","inv.unt.cr"}','Update'),
-- ('inv.unt.dl','Delete Unit','Inventory/Unit/Delete','{"inv.unt.vw","inv.unt.cr","inv.unt.up"}','Delete'),
-- ('inv.pl.vw','View Price List','Inventory/Price List/List',null,'View'),
-- ('inv.pl.cr','Create Price List','Inventory/Price List/Create','{"inv.pl.vw"}','Create'),
-- ('inv.pl.up','Update Price List','Inventory/Price List/Update','{"inv.pl.vw","inv.pl.cr"}','Update'),
-- ('inv.pl.dl','Delete Price List','Inventory/Price List/Delete','{"inv.pl.vw","inv.pl.cr","inv.pl.up"}','Delete'),
-- ('inv.pslt.vw','View PharmaSalt','Inventory/PharmaSalt/List',null,'View'),
-- ('inv.pslt.cr','Create PharmaSalt','Inventory/PharmaSalt/Create','{"inv.pslt.vw"}','Create'),
-- ('inv.pslt.up','Update PharmaSalt','Inventory/PharmaSalt/Update','{"inv.pslt.vw","inv.pslt.cr"}','Update'),
-- ('inv.pslt.dl','Delete PharmaSalt','Inventory/PharmaSalt/Delete','{"inv.pslt.vw","inv.pslt.cr","inv.pslt.up"}','Delete'),
-- ('inv.bom.vw','View BillOfMaterial','Inventory/BillOfMaterial/List',null,'View'),
-- ('inv.bom.cr','Create BillOfMaterial','Inventory/BillOfMaterial/Create','{"inv.bom.vw"}','Create'),
-- ('inv.bom.up','Update BillOfMaterial','Inventory/BillOfMaterial/Update','{"inv.bom.vw","inv.bom.cr"}','Update'),
-- ('inv.bom.dl','Delete BillOfMaterial','Inventory/BillOfMaterial/Delete','{"inv.bom.vw","inv.bom.cr","inv.bom.up"}','Delete'),
-- ('inv.ven.vw','View Vendor','Inventory/Vendor/List',null,'View'),
-- ('inv.ven.cr','Create Vendor','Inventory/Vendor/Create','{"inv.ven.vw"}','Create'),
-- ('inv.ven.up','Update Vendor','Inventory/Vendor/Update','{"inv.ven.vw","inv.ven.cr"}','Update'),
-- ('inv.ven.dl','Delete Vendor','Inventory/Vendor/Delete','{"inv.ven.vw","inv.ven.cr","inv.ven.up"}','Delete'),
-- ('inv.cus.vw','View Customer','Inventory/Customer/List',null,'View'),
-- ('inv.cus.cr','Create Customer','Inventory/Customer/Create','{"inv.cus.vw"}','Create'),
-- ('inv.cus.up','Update Customer','Inventory/Customer/Update','{"inv.cus.vw","inv.cus.cr"}','Update'),
-- ('inv.cus.dl','Delete Customer','Inventory/Customer/Delete','{"inv.cus.vw","inv.cus.cr","inv.cus.up"}','Delete'),
-- ('tag.vw','View Tag','Tag/List',null,'View'),
-- ('tag.cr','Create Tag','Tag/Create','{"tag.vw"}','Create'),
-- ('tag.up','Update Tag','Tag/Update','{"tag.vw","tag.cr"}','Update'),
-- ('tag.dl','Delete Tag','Tag/Delete','{"tag.vw","tag.cr","tag.up"}','Delete'),
-- ('inv.doc.vw','View Doctor','Inventory/Doctor/List',null,'View'),
-- ('inv.doc.cr','Create Doctor','Inventory/Doctor/Create','{"inv.doc.vw"}','Create'),
-- ('inv.doc.up','Update Doctor','Inventory/Doctor/Update','{"inv.doc.vw","inv.doc.cr"}','Update'),
-- ('inv.doc.dl','Delete Doctor','Inventory/Doctor/Delete','{"inv.doc.vw","inv.doc.cr","inv.doc.up"}','Delete'),
-- ('inv.salquot.vw','View Sale Quotation','Inventory/SaleQuotation/List',null,'View'),
-- ('inv.salquot.cr','Create Sale Quotation','Inventory/SaleQuotation/Create','{"inv.salquot.vw"}','Create'),
-- ('inv.salquot.up','Update Sale Quotation','Inventory/SaleQuotation/Update','{"inv.salquot.vw","inv.salquot.cr"}','Update'),
-- ('inv.salquot.dl','Delete Sale Quotation','Inventory/SaleQuotation/Delete','{"inv.salquot.vw","inv.salquot.cr","inv.salquot.up"}','Delete'),
-- ('inv.sal.vw','View Sale','Inventory/Sale/List',null,'View'),
-- ('inv.sal.cr','Create Sale','Inventory/Sale/Create','{"inv.sal.vw"}','Create'),
-- ('inv.sal.up','Update Sale','Inventory/Sale/Update','{"inv.sal.vw","inv.sal.cr"}','Update'),
-- ('inv.sal.dl','Delete Sale','Inventory/Sale/Delete','{"inv.sal.vw","inv.sal.cr","inv.sal.up"}','Delete'),
-- ('inv.sal.cnl','Sale Cancel','Inventory/Sale/Cancel','{"inv.sal.vw"}','Options'),
-- ('inv.crnt.vw','View Credit Note','Inventory/CreditNote/List',null,'View'),
-- ('inv.crnt.cr','Create Credit Note','Inventory/CreditNote/Create','{"inv.crnt.vw"}','Create'),
-- ('inv.crnt.up','Update Credit Note','Inventory/CreditNote/Update','{"inv.crnt.vw","inv.crnt.cr"}','Update'),
-- ('inv.crnt.dl','Delete Credit Note','Inventory/CreditNote/Delete','{"inv.crnt.vw","inv.crnt.cr","inv.crnt.up"}','Delete'),
-- ('inv.crnt.cnl','Credit Note Cancel','Inventory/CreditNote/Cancel','{"inv.crnt.vw"}','Options'),
-- ('inv.pur.vw','View Purchase','Inventory/Purchase/List',null,'View'),
-- ('inv.pur.cr','Create Purchase','Inventory/Purchase/Create','{"inv.pur.vw"}','Create'),
-- ('inv.pur.up','Update Purchase','Inventory/Purchase/Update','{"inv.pur.vw","inv.pur.cr"}','Update'),
-- ('inv.pur.dl','Delete Purchase','Inventory/Purchase/Delete','{"inv.pur.vw","inv.pur.cr","inv.pur.up"}','Delete'),
-- ('inv.pur.cnl','Purchase Cancel','Inventory/Purchase/Cancel','{"inv.pur.vw"}','Options'),
-- ('inv.pur.imp','Purchase Import','Inventory/Purchase/Import','{"inv.pur.vw","inv.pur.cr","inv.pur.up"}','Options'),
-- ('inv.drnt.vw','View Debit Note','Inventory/DebitNote/List',null,'View'),
-- ('inv.drnt.cr','Create Debit Note','Inventory/DebitNote/Create','{"inv.drnt.vw"}','Create'),
-- ('inv.drnt.up','Update Debit Note','Inventory/DebitNote/Update','{"inv.drnt.vw","inv.drnt.cr"}','Update'),
-- ('inv.drnt.dl','Delete Debit Note','Inventory/DebitNote/Delete','{"inv.drnt.vw","inv.drnt.cr","inv.drnt.up"}','Delete'),
-- ('inv.drnt.cnl','Debit Note Cancel','Inventory/DebitNote/Cancel','{"inv.drnt.vw"}','Options'),
-- ('inv.pup.vw','View Personal Use Purchase','Inventory/PersonalUsePurchase/List',null,'View'),
-- ('inv.pup.cr','Create Personal Use Purchase','Inventory/PersonalUsePurchase/Create','{"inv.pup.vw"}','Create'),
-- ('inv.pup.up','Update Personal Use Purchase','Inventory/PersonalUsePurchase/Update','{"inv.pup.vw","inv.pup.cr"}','Update'),
-- ('inv.pup.dl','Delete Personal Use Purchase','Inventory/PersonalUsePurchase/Delete','{"inv.pup.vw","inv.pup.cr","inv.pup.up"}','Delete'),
-- ('inv.stkadj.vw','View Stock Adjustment','Inventory/StockAdjustment/List',null,'View'),
-- ('inv.stkadj.cr','Create Stock Adjustment','Inventory/StockAdjustment/Create','{"inv.stkadj.vw"}','Create'),
-- ('inv.stkadj.up','Update Stock Adjustment','Inventory/StockAdjustment/Update','{"inv.stkadj.vw","inv.stkadj.cr"}','Update'),
-- ('inv.stkadj.dl','Delete Stock Adjustment','Inventory/StockAdjustment/Delete','{"inv.stkadj.vw","inv.stkadj.cr","inv.stkadj.up"}','Delete'),
-- ('inv.stkadj.cnl','Stock Adjustment Cancel','Inventory/StockAdjustment/Cancel','{"inv.stkadj.vw"}','Options'),
-- ('inv.stkded.vw','View Stock Deduction','Inventory/StockDeduction/List',null,'View'),
-- ('inv.stkded.cr','Create Stock Deduction','Inventory/StockDeduction/Create','{"inv.stkded.vw"}','Create'),
-- ('inv.stkded.up','Update Stock Deduction','Inventory/StockDeduction/Update','{"inv.stkded.vw","inv.stkded.cr"}','Update'),
-- ('inv.stkded.dl','Delete Stock Deduction','Inventory/StockDeduction/Delete','{"inv.stkded.vw","inv.stkded.cr","inv.stkded.up"}','Delete'),
-- ('inv.stkadd.vw','View Stock Addition','Inventory/StockAddition/List',null,'View'),
-- ('inv.stkadd.cr','Create Stock Addition','Inventory/StockAddition/Create','{"inv.stkadd.vw"}','Create'),
-- ('inv.stkadd.up','Update Stock Addition','Inventory/StockAddition/Update','{"inv.stkadd.vw","inv.stkadd.cr"}','Update'),
-- ('inv.stkadd.dl','Delete Stock Addition','Inventory/StockAddition/Delete','{"inv.stkadd.vw","inv.stkadd.cr","inv.stkadd.up"}','Delete'),
-- ('inv.mc.vw','View Material Conversion','Inventory/MaterialConversion/List',null,'View'),
-- ('inv.mc.cr','Create Material Conversion','Inventory/MaterialConversion/Create','{"inv.mc.vw"}','Create'),
-- ('inv.mc.up','Update Material Conversion','Inventory/MaterialConversion/Update','{"inv.mc.vw","inv.mc.cr"}','Update'),
-- ('inv.mc.dl','Delete Material Conversion','Inventory/MaterialConversion/Delete','{"inv.mc.vw","inv.mc.cr","inv.mc.up"}','Delete'),
-- ('inv.mc.cnl','Material Conversion Cancel','Inventory/MaterialConversion/Cancel','{"inv.mc.vw"}','Options'),
-- ('inv.mj.vw','View Manufacturing Journal','Inventory/ManufacturingJournal/List',null,'View'),
-- ('inv.mj.cr','Create Manufacturing Journal','Inventory/ManufacturingJournal/Create','{"inv.mj.vw"}','Create'),
-- ('inv.mj.up','Update Manufacturing Journal','Inventory/ManufacturingJournal/Update','{"inv.mj.vw","inv.mj.cr"}','Update'),
-- ('inv.mj.dl','Delete Manufacturing Journal','Inventory/ManufacturingJournal/Delete','{"inv.mj.vw","inv.mj.cr","inv.mj.up"}','Delete'),
-- ('inv.mj.cnl','Manufacturing Journal Cancel','Inventory/ManufacturingJournal/Cancel','{"inv.mj.vw"}','Options'),
-- ('rpt.ac.acbk','Account Book','Report/Account/AccountBook','{"rpt.ac.eftacbk"}','Report'),
-- ('rpt.ac.acout','Account Outstanding','Report/Account/AccountOutstanding',null,'Report'),
-- ('rpt.ac.bnkrcl','Bank Reconcilation','Report/Account/BankReconcilation',null,'Report'),
-- ('rpt.ac.eftacbk','EFT Account Book','Report/Account/AccountBook',null,'Report'),
-- ('rpt.ac.fncl','Financial Report','Report/Account/FinancialReport',null,'Report'),
-- ('rpt.atvt.dybk','Day Book','Report/Activites/DayBook',null,'Report'),
-- ('rpt.ac.cusbk','Customer Book','Report/Account/AccountBook',null,'Report'),
-- ('rpt.ac.vendbk','Vendor Book','Report/Account/AccountBook',null,'Report'),
-- ('rpt.ac.cmpvocanlys','Comparative Voucher Analysis','Report/Account/ComparativeVoucherAnalysis',null,'Report'),
-- ('rpt.inv.invbk','Inventory Book','Report/Inventory/InventoryBook',null,'Report'),
-- ('utly.setstkval','Set Stock Value','Utility/SetStockValue','{"rpt.inv.stkanlys"}','Utility'),
-- ('rpt.inv.stkvalsum','Stock Valuation Summary','Report/Inventory/StockAnalysis','{"rpt.inv.stkanlys"}','Report'),
-- ('rpt.inv.invinfo','Inventory Information','Report/Inventory/InventoryInformation',null,'Report'),
-- ('rpt.sls.pdtwssls','Product wise Sales','Report/Sales/ProductwiseSales',null,'Report'),
-- ('rpt.sls.pdtwspft','Product wise Profit','Report/Sales/ProductwiseProfit','{"rpt.sls.pdtwssls"}','Report'),
-- ('rpt.sls.salanlys','Sale Analysis','Report/Sales/SaleAnalysis',null,'Report'),
-- ('rpt.sls.slsbyinc','Sales by Incharge','Report/Sales/SalesByIncharge',null,'Report'),
-- ('rpt.sls.slreg','Sale Register','Report/Sales/SaleRegister',null,'Report'),
-- ('rpt.sls.cusslsum','Customer Sale Summary','Report/Sales/CustomerSaleSummary',null,'Report'),
-- ('rpt.pur.pureg','Purchase Register','Report/Purchases/PurchaseRegister',null,'Report'),
-- ('rpt.pur.prvprof','Provisional Profit','Report/Purchases/ProvisionalProfit',null,'Report'),
-- ('rpt.dysum','Day Summary','Report/DaySummary',null,'Report'),
-- ('gst.r1.vw','GSTR1 View','GST/R1/View',null,'Report'),
-- ('gst.r1.sav','GSTR1 Push Transactions','GST/R1/Save','{"gst.r1.vw"}','Report'),
-- ('gst.r2.vw','GSTR2 View Return Details','GST/R2/View',null,'Report'),
-- ('gst.r2.rcl','GSTR2 Reconcile Transactions','GST/R2/Reconcile','{"gst.r2.vw"}','Report'),
-- ('utly.chq.bk','Cheque Book','Utility/Cheque/Book',null,'Utility'),
-- ('utly.lbl.bat','Batch Label','Utility/Label/Batch',null,'Utility'),
-- ('utly.tly.exp','Tally Export','Utility/Tally/Export',null,'Utility'),
-- ('utly.lbl.rck','Rack Label','Utility/Label/Rack',null,'Utility'),
-- ('adm.brn.vw','View Branch','Administration/Branch/View',null,'View,Administration'),
-- ('adm.brn.cr','Create Branch','Administration/Branch/Create','{"adm.brn.vw"}','Create,Administration'),
-- ('adm.brn.up','Update Branch','Administration/Branch/Update','{"adm.brn.vw","adm.brn.cr"}','Update,Administration'),
-- ('adm.brn.dl','Delete Branch','Administration/Branch/Delete','{"adm.brn.vw","adm.brn.cr","adm.brn.up"}','Delete,Administration'),
-- ('adm.dc.vw','View Desktop Client','Administration/DesktopClient/View',null,'View,Administration'),
-- ('adm.dc.cr','Create Desktop Client','Administration/DesktopClient/Create','{"adm.dc.vw"}','Create,Administration'),
-- ('adm.dc.up','Update Desktop Client','Administration/DesktopClient/Update','{"adm.dc.vw","adm.dc.cr"}','Update,Administration'),
-- ('adm.dc.dl','Delete Desktop Client','Administration/DesktopClient/Delete','{"adm.dc.vw","adm.dc.cr","adm.dc.up"}','Delete,Administration'),
-- ('adm.dc.tkgn','Desktop Client Token Generate','Administration/DesktopClient/TokenGenerate','{"adm.dc.vw"}','Options,Administration'),
-- ('utly.ofv.vw','View Offline Voucher','Utility/OfflineVoucher/View',null,'View,Utility'),
-- ('utly.ofv.dl','Delete Offline Voucher','Utility/OfflineVoucher/Delete','{"utly.ofv.vw"}','Delete,Utility'),
-- ('adm.gstrgn.vw','View GST Registration','Administration/GSTRegistration/View',null,'View,Administration'),
-- ('adm.gstrgn.cr','Create GST Registration','Administration/GSTRegistration/Create','{"adm.gstrgn.vw"}','Create,Administration'),
-- ('adm.gstrgn.up','Update GST Registration','Administration/GSTRegistration/Update','{"adm.gstrgn.vw","adm.gstrgn.cr"}','Update,Administration'),
-- ('adm.gstrgn.dl','Delete GST Registration','Administration/GSTRegistration/Delete','{"adm.gstrgn.vw","adm.gstrgn.cr","adm.gstrgn.up"}','Delete,Administration'),
-- ('adm.mem.vw','View Member','Administration/Member/View',null,'View,Administration'),
-- ('adm.mem.cr','Create Member','Administration/Member/Create','{"adm.mem.vw"}','Create,Administration'),
-- ('adm.mem.up','Update Member','Administration/Member/Update','{"adm.mem.vw","adm.mem.cr"}','Update,Administration'),
-- ('adm.mem.dl','Delete Member','Administration/Member/Delete','{"adm.mem.vw","adm.mem.cr","adm.mem.up"}','Update,Administration'),
-- ('adm.role.vw','View Role','Administration/Role/View',null,'View,Administration'),
-- ('adm.role.cr','Create Role','Administration/Role/Create','{"adm.role.vw"}','Create,Administration'),
-- ('adm.role.up','Update Role','Administration/Role/Update','{"adm.role.vw","adm.role.cr"}','Update,Administration'),
-- ('adm.role.dl','Delete Role','Administration/Role/Delete','{"adm.role.vw","adm.role.cr","adm.role.up"}','Update,Administration'),
-- ('adm.conf.fyr','Financial Year','Administration/Configuration/FinancialYear',null,'Administration,Create,Update'),
-- ('prntmpl','PrintTemplate Create and Update','PrintTemplate',null,'Administration,Create,Update,Options'),
-- ('vtyp.vw','View VoucherType','VoucherType/View',null,'View'),
-- ('vtyp.cr','Create VoucherType','VoucherType/Create','{"vtyp.vw"}','Create'),
-- ('vtyp.up','Update VoucherType','VoucherType/Update','{"vtyp.vw","vtyp.cr"}','Update'),
-- ('vtyp.dl','Delete VoucherType','VoucherType/Delete','{"vtyp.vw","vtyp.cr","vtyp.up"}','Delete'),
-- ('bat.up','Update Batch','Batch/Update',null,'Update'),
-- ('rpt.schdrg','Scheduled Drug','Report/Scheduled Drug',null,'Report'),
-- ('rpt.stkanlys','Stock Analysis','Report/Stock Analysis',null,'Report'),
-- ('rpt.pur.venstkanlys','Vendor Stock Analysis','Report/Purchases/VendorStockAnalysis',null,'Report'),
-- ('rpt.actagvch','Account Tagged Voucher','Report/Account/TaggedVoucher',null,'Report'),
-- ('rpt.invtagvch','Inventory Tagged Voucher','Report/Inventory/TaggedVoucher',null,'Report'),
-- ('ac.nop.vw','View Nature of payment','Accounting/Nature Of Payment/List',null,'View'),
-- ('ac.nop.cr','Create Nature Of Payment','Accounting/Nature Of Payment/Create','{"ac.nop.vw"}','Create'),
-- ('ac.nop.up','Update Nature Of Payment','Accounting/Nature Of Payment/Update','{"ac.nop.vw","ac.nop.cr"}','Update'),
-- ('ac.nop.dl','Delete Nature Of Payment','Accounting/Nature Of Payment/Delete','{"ac.nop.vw","ac.nop.cr","ac.nop.up"}','Delete'),
-- ('adm.div.vw', 'View Division', 'Division/View',null,'View,Administration'),
-- ('adm.div.cr', 'Create Division','Division/Create','{"adm.div.vw"}','Create,Administration'),
-- ('adm.div.up', 'Update Division', 'Division/Update','{"adm.div.vw","adm.div.cr"}','Update,Administration'),
-- ('adm.div.dl', 'Delete Division', 'Division/Delete','{"adm.div.vw","adm.div.cr","adm.div.up"}','Delete,Administration'),
-- ('adm.aptg.vw', 'View Approval Tag', 'Approval Tag/View',null,'View,Administration'),
-- ('adm.aptg.cr', 'Create Approval Tag', 'Approval Tag/Create','{"adm.aptg.vw"}','Create,Administration'),
-- ('adm.aptg.up', 'Update Approval Tag', 'Approval Tag/Update','{"adm.aptg.vw","adm.aptg.cr"}','Update,Administration'),
-- ('adm.aptg.dl', 'Delete Approval Tag', 'Approval Tag/Delete','{"adm.aptg.vw","adm.aptg.cr","adm.aptg.up"}','Delete,Administration'),
-- ('adm.rptg.vw', 'View Report Tag', 'Report Tag/View',null,'View,Administration'),
-- ('adm.rptg.cr', 'Create Report Tag', 'Report Tag/Create','{"adm.rptg.vw"}','Create,Administration'),
-- ('adm.rptg.up', 'Update Report Tag', 'Report Tag/Update','{"adm.rptg.vw","adm.rptg.cr"}','Update,Administration'),
-- ('adm.rptg.dl', 'Delete Report Tag', 'Report Tag/Delete','{"adm.rptg.vw","adm.rptg.cr","adm.rptg.up"}','Delete,Administration'),
-- ('adm.rptg.mp', 'Mapping Report Tag', 'Report Tag/Mapping','{"adm.rptg.vw","adm.rptg.cr","adm.rptg.up"}','Create,Update,Administration'),
-- ('ac.bnk.vw', 'View Bank', 'Bank/View',null,'View'),
-- ('ac.bnk.cr', 'Create Bank', 'Bank/Create','{"ac.bnk.vw"}','Create'),
-- ('ac.bnk.up', 'Update Bank', 'Bank/Update','{"ac.bnk.vw","ac.bnk.cr"}','Update'),
-- ('ac.bnk.dl', 'Delete Bank', 'Bank/Delete','{"ac.bnk.vw","ac.bnk.cr","ac.bnk.up"}','Delete'),
-- ('ac.bnkbnf.vw', 'View Bank Beneficiary', 'BankBeneficiary/View',null,'View'),
-- ('ac.bnkbnf.cr', 'Create Bank Beneficiary', 'BankBeneficiary/Create','{"ac.bnkbnf.vw"}','Create'),
-- ('ac.bnkbnf.up', 'Update Bank Beneficiary', 'BankBeneficiary/Update','{"ac.bnkbnf.vw","ac.bnkbnf.cr"}','Update'),
-- ('ac.bnkbnf.dl', 'Delete Bank Beneficiary', 'BankBeneficiary/Delete','{"ac.bnkbnf.vw","ac.bnkbnf.cr","ac.bnkbnf.up"}','Delete'),
-- ('ac.gdsinw.vw', 'View Goods Inward', 'GoodsInward/View',null,'View'),
-- ('ac.gdsinw.cr', 'Create Goods Inward', 'GoodsInward/Create','{"ac.gdsinw.vw"}','Create'),
-- ('ac.gdsinw.up', 'Update Goods Inward', 'GoodsInward/Update','{"ac.gdsinw.vw","ac.gdsinw.cr"}','Update'),
-- ('ac.gdsinw.dl', 'Delete Goods Inward', 'GoodsInward/Delete','{"ac.gdsinw.vw","ac.gdsinw.cr","ac.gdsinw.up"}','Delete'),
-- ('ac.gdsinw.apv', 'Approve Goods Inward', 'GoodsInward/Approve','{"ac.gdsinw.vw"}','Update'),
-- ('adm.gftitm.vw', 'View Gift Voucher Item', 'GiftVoucherItem/View',null,'View,Administration'),
-- ('adm.gftitm.cr', 'Create Gift Voucher Item', 'GiftVoucherItem/Create','{"adm.gftitm.vw"}','Create,Administration'),
-- ('adm.gftitm.up', 'Update Gift Voucher Item', 'GiftVoucherItem/Update','{"adm.gftitm.vw","adm.gftitm.cr"}','Update,Administration'),
-- ('adm.gftitm.dl', 'Delete Gift Voucher Item', 'GiftVoucherItem/Delete','{"adm.gftitm.vw","adm.gftitm.cr","adm.gftitm.up"}','Delete,Administration'),
-- ('ac.gftvch.vw', 'View Gift Voucher', 'GiftVoucher/View',null,'View'),
-- ('ac.gftvch.cr', 'Create Gift Voucher', 'GiftVoucher/Create','{"ac.gftvch.vw"}','Create'),
-- ('ac.gftvch.up', 'Update Gift Voucher', 'GiftVoucher/Update','{"ac.gftvch.vw","ac.gftvch.cr"}','Update'),
-- ('ac.gftvch.dl', 'Delete Gift Voucher', 'GiftVoucher/Delete','{"ac.gftvch.vw","ac.gftvch.cr","ac.gftvch.up"}','Delete'),
-- ('ac.tp.vw', 'View Transport', 'Transport/View',null,'View'),
-- ('ac.tp.cr', 'Create Transport', 'Transport/Create','{"ac.tp.vw"}','Create'),
-- ('ac.tp.up', 'Update Transport', 'Transport/Update','{"ac.tp.vw","ac.tp.cr"}','Update'),
-- ('ac.tp.dl', 'Delete Transport', 'Transport/Delete','{"ac.tp.vw","ac.tp.cr","ac.tp.up"}','Delete'),
-- ('inv.off.vw', 'View Offer Management', 'OfferManagement/View',null,'View'),
-- ('inv.off.cr', 'Create Offer Management', 'OfferManagement/Create','{"inv.off.vw"}','Create'),
-- ('inv.off.up', 'Update Offer Management', 'OfferManagement/Update','{"inv.off.vw","inv.off.cr"}','Update'),
-- ('inv.off.dl', 'Delete Offer Management', 'OfferManagement/Delete','{"inv.off.vw","inv.off.cr","inv.off.up"}','Delete'),
-- ('ac.memo.vw', 'View Memorandum', 'Memorandum/View',null,'View'),
-- ('ac.memo.cr', 'Create Memorandum', 'Memorandum/Create','{"ac.memo.vw"}','Create'),
-- ('ac.memo.up', 'Update Memorandum', 'Memorandum/Update','{"ac.memo.vw","ac.memo.cr"}','Update'),
-- ('ac.memo.dl', 'Delete Memorandum', 'Memorandum/Delete','{"ac.memo.vw","ac.memo.cr","ac.memo.up"}','Delete'),
-- ('adm.pos.vw', 'View Pos Server', 'PosServer/View',null,'View,Administration'),
-- ('adm.pos.cr', 'Create Pos Server', 'PosServer/Create','{"adm.pos.vw"}','Create,Administration'),
-- ('adm.pos.up', 'Update Pos Server', 'PosServer/Update','{"adm.pos.vw","adm.pos.cr"}','Update,Administration'),
-- ('adm.pos.dl', 'Delete Pos Server', 'PosServer/Delete','{"adm.pos.vw","adm.pos.cr","adm.pos.up"}','Delete,Administration'),
-- ('adm.pos.tkgn','Pos Server Token Generate','Administration/PosServer/TokenGenerate','{"adm.pos.vw"}','Options,Administration'),
-- ('adm.counter.vw', 'View Pos Counter', 'PosCounter/View',null,'View,Administration'),
-- ('adm.counter.cr', 'Create Pos Counter', 'PosCounter/Create','{"adm.counter.vw"}','Create,Administration'),
-- ('adm.counter.up', 'Update Pos Counter', 'PosCounter/Update','{"adm.counter.vw","adm.counter.cr"}','Update,Administration'),
-- ('rpt.vchreg', 'Voucher Register', 'Report/VoucherRegister',null,'Report'),
-- ('inv.dsprk.vw','View DisplayRack','DisplayRack/View',null,'View'),
-- ('inv.dsprk.cr','Create DisplayRack','DisplayRack/Create','{"inv.dsprk.vw"}','Create'),
-- ('inv.dsprk.up','Update DisplayRack','DisplayRack/Update','{"inv.dsprk.vw","inv.dsprk.cr"}','Update'),
-- ('inv.dsprk.dl','Delete DisplayRack','DisplayRack/Delete','{"inv.dsprk.vw","inv.dsprk.cr","inv.dsprk.up"}','Delete'),
-- ('inv.stkloc.vw','View StockLocation','StockLocation/View',null,'View'),
-- ('inv.stkloc.cr','Create StockLocation','StockLocation/Create','{"inv.stkloc.vw"}','Create'),
-- ('inv.stkloc.up','Update StockLocation','StockLocation/Update','{"inv.stkloc.vw","inv.stkloc.cr"}','Update'),
-- ('inv.stkloc.dl','Delete StockLocation','StockLocation/Delete','{"inv.stkloc.vw","inv.stkloc.cr","inv.stkloc.up"}','Delete'),
-- ('ac.ca.vw','View Customer Advance','Customer Advance/View',null,'View'),
-- ('ac.ca.cr','Create Customer Advance','Customer Advance/Create','{"ac.ca.vw"}','Create'),
-- ('ac.ca.up','Update Customer Advance','Customer Advance/Update','{"ac.ca.vw","ac.ca.cr"}','Update'),
-- ('ac.ca.dl','Delete Customer Advance','Customer Advance/Delete','{"ac.ca.vw","ac.ca.cr","ac.ca.up"}','Delete'),
-- ('rpt.inv.reorder','Inventory Reorder','Report/Inventory/Reorder',null,'Report');
--##
insert into warehouse (name) values ('Default');
--##
insert into voucher_type (id, name, config, is_default, base_type) overriding system value
values (1, 'Payment', '{ "payment": { "printAfterSave": false } }', true, 'PAYMENT'),
       (2, 'Receipt', '{ "receipt": { "printAfterSave": false } }', true, 'RECEIPT'),
       (3, 'Contra',  '{ "contra":  { "printAfterSave": false } }', true, 'CONTRA'),
       (4, 'Journal', '{ "journal": { "printAfterSave": false } }', true, 'JOURNAL'),
       (5, 'Sale', '{
         "sale": {
           "account": {
             "printAfterSave": false
           },
           "inventory": {
             "cashRegisterEnabled": false,
             "warehouseEnabled": false,
             "hideRack": false,
             "hideMrpInBatchModal": false,
             "rateEditable": false,
             "taxEditable": false,
             "discountEditable": false,
             "unitEditable": false,
             "billDiscountEditable": false,
             "printAfterSave": false,
             "setFocusOnInventory": false,
             "autoSelectBatch": false,
             "setDefaultQty": false,
             "enableSilentPrintMode": false,
             "allowCreditCustomer": false,
             "enableSaleIncharge": false,
             "voucherwiseSaleIncharge": false,
             "freezeSaleInchargeForVoucher": false,
             "barcodeEnabled": false,
             "customerFormQuickCreate": false,
             "enableExchange": false,
             "enableAdvance": false,
             "enableEmi": false,
             "setLooseQty": false
           }
         }
       }', true, 'SALE'),
       (6, 'Credit Note', '{
         "creditNote": {
           "account": {
             "printAfterSave": false
           },
           "inventory": {
             "cashRegisterEnabled": false,
             "warehouseEnabled": false,
             "rateEditable": false,
             "taxEditable": false,
             "discountEditable": false,
             "unitEditable": false,
             "billDiscountEditable": false,
             "printAfterSave": false,
             "enableSilentPrintMode": false,
             "allowCreditCustomer": false,
             "enableSaleIncharge": false,
             "voucherwiseSaleIncharge": false,
             "freezeSaleInchargeForVoucher": false,
             "barcodeEnabled": false,
             "enableExp": false,
             "customerFormQuickCreate": false,
             "printCustomerCopy": false,
             "invoiceNoRequired": false,
             "isExchangeVoucher": false
           }
         }
       }', true, 'CREDIT_NOTE'),
       (7, 'Purchase', '{
         "purchase": {
           "account": {
             "printAfterSave": false
           },
           "inventory": {
             "printAfterSave": false,
             "sRateMrpRequired": false,
             "sRateAsMrp": false,
             "enableSilentPrintMode": false,
             "allowCreditVendor": true,
             "barcodeEnabled": false,
             "preventLoss": false,
             "taxHide": false,
             "enableGin": false,
             "enableExpiry": false,
             "expiryRequired": false,
             "isExchangeVoucher": false,
             "enableBillDetail": true,
             "enableAutomaticRoundedOff": false,
             "enableWeightBill": false,
             "allowNewRefOnly": false,
             "billFormat": "NORMAL",
             "setLooseQty": false
           }
         }
       }', true, 'PURCHASE'),
       (8, 'Debit Note', '{
         "debitNote": {
           "account": {
             "printAfterSave": false
           },
           "inventory": {
             "cashRegisterEnabled": false,
             "warehouseEnabled": false,
             "rateEditable": false,
             "taxEditable": false,
             "discountEditable": false,
             "printAfterSave": false,
             "enableSilentPrintMode": false,
             "allowCreditVendor": false,
             "barcodeEnabled": false,
             "enableExp": false,
             "billNoRequired": false
           }
         }
       }', true, 'DEBIT_NOTE'),
       (9, 'Sale Quotation', '{
         "saleQuotation": {
           "rateEditable": false,
           "taxEditable": false,
           "discountEditable": false,
           "unitEditable": false,
           "billDiscountEditable": false,
           "enableSilentPrintMode": false,
           "printAfterSave": false,
           "barcodeEnabled": false,
           "enableExp": false
         }
       }', true, 'SALE_QUOTATION'),
       (10, 'Stock Adjustment', '{
         "stockAdjustment": {
           "enableSilentPrintMode": false,
           "printAfterSave": false,
           "barcodeEnabled": false,
           "enableExp": false
         }
       }', true, 'STOCK_ADJUSTMENT'),
       (11, 'Stock Deduction', '{
         "stockDeduction": {
           "enableSilentPrintMode": false,
           "printAfterSave": false,
           "barcodeEnabled": false,
           "enableExp": false,
           "altBranchRequired": false
         }
       }', true, 'STOCK_DEDUCTION'),
       (12, 'Stock Addition', '{
         "stockAddition": {
           "enableSilentPrintMode": false,
           "printAfterSave": false,
           "barcodeEnabled": false,
           "enableExp": false,
           "altBranchRequired": false
         }
       }', true, 'STOCK_ADDITION'),
       (13, 'Material Conversion', '{
         "materialConversion": {
           "enableSilentPrintMode": false,
           "printAfterSave": false,
           "barcodeEnabled": false,
           "enableExp": false
         }
       }', true, 'MATERIAL_CONVERSION'),
       (14, 'Manufacturing Journal', '{
         "manufacturingJournal": {
           "barcodeEnabled": false
         }
       }', true, 'MANUFACTURING_JOURNAL'),
       (15, 'Memo', '{
         "memo": {
           "expenseOnly": false,
           "printAfterSave": false,
           "openChequeBookDetail": false
         }
       }', true, 'MEMO'),
       (16, 'Wastage', '{
         "wastage": {
           "enableSilentPrintMode": false,
           "printAfterSave": false,
           "barcodeEnabled": false,
           "enableExp": false
         }
       }', true, 'WASTAGE'),
       (17, 'Goods Inward Note', '{
         "goodsInwardNote": {
           "printAfterSave": false,
           "enableSilentPrintMode": false
         }
       }', true, 'GOODS_INWARD_NOTE'),
       (18, 'Gift Voucher', '{
         "giftVoucher": {
           "printAfterSave": false,
           "enableSilentPrintMode": false
         }
       }', true, 'GIFT_VOUCHER'),
       (19, 'Purchased Goods For Personal Use', '{
         "personalUsePurchase": {
           "expenseAccount": null
         }
       }', true, 'PERSONAL_USE_PURCHASE'),
       (20, 'Customer Advance', '{
         "customerAdvance": {
           "printAfterSave": false,
           "enableSilentPrintMode": false
         }
       }', true, 'CUSTOMER_ADVANCE');
--##
insert into permission (name, resource, action, fields) values
('Select Account Type','account_type','select',null),
('Insert Account Type','account_type','insert','{"name","parent_id","description"}'),
('Update Account Type','account_type','update','{"name","description"}'),
('Delete Account Type','account_type','delete',null),
('Select Category','category','select',null),
('Update Category','category','update','{"category","active","sort_order"}'),
('Category Bulk Update','category_bulk_update','execute',null),
('Select Warehouse','warehouse','select',null),
('Insert Warehouse','warehouse','insert','{"name", "mobile", "email", "telephone", "address", "city", "pincode", "state_id", "country_id"}'),
('Update Warehouse','warehouse','update','{"name", "mobile", "email", "telephone", "address", "city", "pincode", "state_id", "country_id"}'),
('Delete Warehouse','warehouse','delete',null),
('Select Member','member','select',null),
('Insert Member','member','insert','{"name", "pass", "remote_access", "settings", "role", "user_id", "nick_name"}'),
('Update Member','member','update','{"name", "pass", "remote_access", "settings", "role", "user_id", "nick_name"}'),
('Member Profile','member_profile','execute',null),
('Select Member Role','member_role','select',null),
('Insert Member Role','member_role','insert','{"name", "perms"}'),
('Update Member Role','member_role','update','{"name", "perms"}'),
('Select Approval Tag','approval_tag','select',null),
('Insert Approval Tag','approval_tag','insert','{"name", "members"}'),
('Update Approval Tag','approval_tag','update','{"name", "members"}'),
('Delete Approval Tag','approval_tag','delete',null),
('Select Tds Nature of Payment','tds_nature_of_payment','select',null),
('Insert Tds Nature of Payment','tds_nature_of_payment','insert','{"name", "section", "ind_huf_rate", "ind_huf_rate_wo_pan", "other_deductee_rate", "other_deductee_rate_wo_pan", "threshold"}'),
('Update Tds Nature of Payment','tds_nature_of_payment','update','{"name", "section", "ind_huf_rate", "ind_huf_rate_wo_pan", "other_deductee_rate", "other_deductee_rate_wo_pan", "threshold"}'),
('Delete Tds Nature of Payment','tds_nature_of_payment','delete',null),
('Select Bank Beneficiary','bank_beneficiary','select',null),
('Insert Bank Beneficiary','bank_beneficiary','insert','{"account_no", "bank_name", "branch_name", "ifs_code", "account_type", "account_holder_name"}'),
('Update Bank Beneficiary','bank_beneficiary','update','{"account_no", "bank_name", "branch_name", "ifs_code", "account_type", "account_holder_name"}'),
('Delete Bank Beneficiary','bank_beneficiary','delete',null),
('Select Doctor','doctor','select',null),
('Insert Doctor','doctor','insert','{"name", "license_no"}'),
('Update Doctor','doctor','update','{"name", "license_no"}'),
('Delete Doctor','doctor','delete',null),
('Select Stock Location','stock_location','select',null),
('Insert Stock Location','stock_location','insert','{"name"}'),
('Update Stock Location','stock_location','update','{"name"}'),
('Delete Stock Location','stock_location','delete',null),
('Select Display Rack','display_rack','select',null),
('Insert Display Rack','display_rack','insert','{"name"}'),
('Update Display Rack','display_rack','update','{"name"}'),
('Delete Display Rack','display_rack','delete',null),
('Select Tag','tag','select',null),
('Insert Tag','tag','insert','{"name"}'),
('Update Tag','tag','update','{"name"}'),
('Delete Tag','tag','delete',null),
('Select Manufacturer','manufacturer','select',null),
('Insert Manufacturer','manufacturer','insert','{"name", "mobile", "email", "telephone"}'),
('Update Manufacturer','manufacturer','update','{"name", "mobile", "email", "telephone"}'),
('Delete Manufacturer','manufacturer','delete',null),
('Select Sale Incharge','sale_incharge','select',null),
('Insert Sale Incharge','sale_incharge','insert','{"name", "code"}'),
('Update Sale Incharge','sale_incharge','update','{"name", "code"}'),
('Delete Sale Incharge','sale_incharge','delete',null),
('Select Price List','price_list','select',null),
('Insert Price List','price_list','insert','{"name", "customer_tag_id"}'),
('Update Price List','price_list','update','{"name", "customer_tag_id"}'),
('Delete Price List','price_list','delete',null),
('Select Price List Condition','price_list_condition','select',null),
('Insert Price List Condition','price_list_condition','insert',null),
('Update Price List Condition','price_list_condition','update','{"apply_on", "computation", "priority", 
              "min_qty", "min_value", "value", "branch_id", "inventory_tags", "batches","inventory_id",
              "category1_id", "category2_id", "category3_id", "category4_id", "category5_id",
              "category6_id", "category7_id", "category8_id", "category9_id", "category10_id"}'),
('Delete Price List Condition','price_list_condition','delete',null),
('Select Print Template','print_template','select',null),
('Insert Print Template','print_template','insert','{"name", "config", "layout", "voucher_mode"}'),
('Update Print Template','print_template','update','{"name", "config", "layout", "voucher_mode"}'),
('Delete Print Template','print_template','delete',null),
('Select Gst Registration','gst_registration','select',null),
('Insert Gst Registration','gst_registration','insert','{"reg_type", "gst_no", "state_id", "username", "email", "e_invoice_username", "e_password"}'),
('Update Gst Registration','gst_registration','update','{"reg_type", "gst_no", "state_id", "username", "email", "e_invoice_username", "e_password"}'),
('Select Account','account','select',null),
('Insert Account','account','insert','{"name", "account_type_id", "alias_name", "cheque_in_favour_of", "description",
    "commission", "gst_reg_type", "gst_location_id", "gst_no", "gst_is_exempted", "gst_exempted_desc", "sac_code",
    "bill_wise_detail", "is_commission_discounted", "due_based_on", "due_days", "credit_limit", "pan_no",
    "aadhar_no", "mobile", "email", "contact_person", "address", "city", "pincode", "category1", "category2", "category3", "category4",
    "category5", "state_id", "country_id", "bank_beneficiary_id", "agent_id", "commission_account_id", "gst_tax_id",
    "tds_nature_of_payment_id", "tds_deductee_type_id"}'),
('Update Account','account','update','{"name", "alias_name", "cheque_in_favour_of", "description",
    "commission", "gst_reg_type", "gst_location_id", "gst_no", "gst_is_exempted", "gst_exempted_desc", "sac_code",
    "bill_wise_detail", "is_commission_discounted", "due_based_on", "due_days", "credit_limit", "pan_no",
    "aadhar_no", "mobile", "email", "contact_person", "address", "city", "pincode", "category1", "category2", "category3", "category4",
    "category5", "state_id", "country_id", "bank_beneficiary_id", "agent_id", "commission_account_id", "gst_tax_id",
    "tds_nature_of_payment_id", "tds_deductee_type_id"}'),
('Delete Account','account','delete',null),
('Select Customer','customer','select',null),
('Insert Customer','customer','insert','{"name", "short_name", "pan_no", "aadhar_no", "gst_reg_type", "gst_location_id", "gst_no", "mobile", "alternate_mobile",
    "email", "telephone", "contact_person", "address", "city", "pincode", "state_id", "country_id", "bank_beneficiary_id", "delivery_address",
    "tracking_account", "tracking_account_type_id", "enable_loyalty_point", "agent_id", "commission_account_id", "commission", "is_commission_discounted",
    "bill_wise_detail", "tags", "due_based_on", "due_days", "credit_limit"}'),
('Update Customer','customer','update','{"name", "short_name", "pan_no", "aadhar_no", "gst_reg_type", "gst_location_id", "gst_no", "mobile", "alternate_mobile",
    "email", "telephone", "contact_person", "address", "city", "pincode", "state_id", "country_id", "bank_beneficiary_id", "delivery_address",
    "enable_loyalty_point", "agent_id", "commission_account_id", "commission", "is_commission_discounted",
    "bill_wise_detail", "tags", "due_based_on", "due_days", "credit_limit"}'),
('Delete Customer','customer','delete',null),

('Select Branch','branch','select',null),
('Insert Branch','branch','insert','{"name", "mobile", "alternate_mobile", "email", "telephone", "contact_person", "address", "city", "pincode", "state_id",
    "country_id", "gst_registration_id", "voucher_no_prefix", "misc", "members", "account_id"}'),
('Update Branch','branch','update','{"name", "mobile", "alternate_mobile", "email", "telephone", "contact_person", "address", "city", "pincode", "state_id",
    "country_id", "gst_registration_id", "voucher_no_prefix", "misc", "members"}'),
('Delete Branch','branch','delete',null),

('Select Vendor','vendor','select',null),
('Insert Vendor','vendor','insert','{"name", "short_name", "pan_no", "aadhar_no", "gst_reg_type", "gst_location_id", "gst_no", "mobile", "alternate_mobile",
    "email", "telephone", "contact_person", "address", "city", "pincode", "state_id", "country_id", "bank_beneficiary_id", "tracking_account", "tracking_account_type_id",
    "agent_id", "commission_account_id", "commission", "is_commission_discounted", "bill_wise_detail", "due_based_on",
    "due_days", "credit_limit", "tds_deductee_type_id"}'),
('Update Vendor','vendor','update','{"name", "short_name", "pan_no", "aadhar_no", "gst_reg_type", "gst_location_id", "gst_no", "mobile", "alternate_mobile",
    "email", "telephone", "contact_person", "address", "city", "pincode", "state_id", "country_id", "bank_beneficiary_id", 
    "agent_id", "commission_account_id", "commission", "is_commission_discounted", "bill_wise_detail", "due_based_on",
    "due_days", "credit_limit", "tds_deductee_type_id"}'),
('Delete Vendor','vendor','delete',null),

('Select Stock Value','stock_value','select',null),
('Select Stock Value','stock_value','insert',null),
('Select Stock Value','stock_value','update',null),
('Select Stock Value','stock_value','delte',null),

('Select Offer Management','offer_management','select',null),
('Insert Offer Management','offer_management','insert','{"name", "conditions", "rewards", "branch_id", "price_list_id", "start_date", "end_date"}'),
('Update Offer Management','offer_management','update','{"name", "conditions", "rewards", "branch_id", "price_list_id", "start_date", "end_date"}'),
('Delete Offer Management','offer_management','delete',null),
('Select Offer Management','offer_management_condition','select',null),
('Select Offer Management','offer_management_reward','select',null),

('Select Transport','transport','select',null),
('Insert Transport','transport','insert','{"name", "mobile", "email", "telephone"}'),
('Update Transport','transport','update','{"name", "mobile", "email", "telephone"}'),
('Delete Transport','transport','delete',null),

('Select Pos Server','pos_server','select',null),
('Insert Pos Server','pos_server','insert','{"name", "branch_id", "mode"}'),
('Update Pos Server','pos_server','update','{"name", "mode", "is_active"}'),
('Delete Pos Server','pos_server','delete',null),

('Select Desktop Client','desktop_client','select',null),
('Insert Desktop Client','desktop_client','insert','{"name","branches"}'),
('Update Desktop Client','desktop_client','update','{"name","branches"}'),
('Delete Desktop Client','desktop_client','delete',null),

('Select Unit','unit','select',null),
('Insert Unit','unit','insert','{"name", "uqc_id", "symbol", "precision", "conversions"}'),
('Update Unit','unit','update','{"name", "uqc_id", "symbol", "precision", "conversions"}'),
('Delete Unit','unit','delete',null),
('Select Unit Conversion','unit_conversion','select',null),

('Select Category Option','category_option','select',null),
('Insert Category Option','category_option','insert','{"category_id", "name", "active"}'),
('Update Category Option','category_option','update','{"category_id", "name", "active"}'),
('Delete Category Option','category_option','delete',null),

('Select Division','division','select',null),
('Insert Division','division','insert','{"name"}'),
('Update Division','division','update','{"name"}'),
('Delete Division','division','delete',null),

('Select Gift Coupon','gift_coupon','select',null),

('Select Pos Counter','pos_counter','select',null),
('Insert Pos Counter','pos_counter','insert','{"name"}'),
('Update Pos Counter','pos_counter','update','{"name"}'),

('Select Voucher Type','voucher_type','select',null),
('Insert Voucher Type','voucher_type','insert','{"name", "prefix", "sequence_id", "base_type", "config", "members", "approval"}'),
('Update Voucher Type','voucher_type','update','{"name", "prefix", "sequence_id", "config", "members", "approval"}'),
('Delete Voucher Type','voucher_type','delete',null),

('Select Inventory','inventory','select',null),
('Insert Inventory','inventory','insert','{"name", "division_id", "inventory_type", "allow_negative_stock", "gst_tax_id", "unit_id", "loose_qty",
    "reorder_inventory_id", "bulk_inventory_id", "qty", "sale_unit_id", "purchase_unit_id", "cess", "purchase_config",
    "sale_config", "barcodes", "tags", "hsn_code", "description", "manufacturer_id", "manufacturer_name", "vendor_id",
    "vendor_name", "vendors", "salts", "set_rate_values_via_purchase", "apply_s_rate_from_master_for_sale",
    "category1", "category2", "category3", "category4", "category5", "category6", "category7", "category8",
    "category9", "category10"}'),
('Update Inventory','inventory','update','{"name", "inventory_type", "allow_negative_stock", "gst_tax_id", "unit_id",
    "reorder_inventory_id", "bulk_inventory_id", "qty", "sale_unit_id", "purchase_unit_id", "cess", "purchase_config",
    "sale_config", "barcodes", "tags", "hsn_code", "description", "manufacturer_id", "manufacturer_name", "vendor_id",
    "vendor_name", "vendors", "salts", "set_rate_values_via_purchase", "apply_s_rate_from_master_for_sale",
    "category1", "category2", "category3", "category4", "category5", "category6", "category7", "category8",
    "category9", "category10"}'),
('Delete Inventory','inventory','delete',null),

('Select Inventory Branch Detail','inventory_branch_detail','select',null),
('Insert Inventory Branch Detail','inventory_branch_detail','insert','{"inventory_id", "inventory_name", "branch_id", "branch_name", "stock_location_id",
    "s_disc", "discount_1", "discount_2", "vendor_id", "s_customer_disc", "mrp_price_list", "s_rate_price_list",
    "nlc_price_list", "mrp", "s_rate", "p_rate_tax_inc", "p_rate", "landing_cost", "nlc", "stock", "reorder_inventory_id",
    "reorder_mode", "reorder_level", "min_order", "max_order"}'),
('Update Inventory Branch Detail','inventory_branch_detail','update','{"inventory_name", "branch_name", "stock_location_id",
    "s_disc", "discount_1", "discount_2", "vendor_id", "s_customer_disc", "mrp_price_list", "s_rate_price_list",
    "nlc_price_list", "mrp", "s_rate", "p_rate_tax_inc", "p_rate", "landing_cost", "nlc", "stock", "reorder_inventory_id",
    "reorder_mode", "reorder_level", "min_order", "max_order"}'),

('Merge Inventory','merge_inventory','execute',null),

('Select Approval Log','approval_log','select',null),

('Select Financial Year','financial_year','select',null),
('Create Financial Year','create_financial_year','execute',null),

('Select Batch','batch','select',null),
('Update Batch','batch','update','{"batch_no", "expiry", "s_rate", "mrp"}'),
('Select Batch Label','batch_label','select',null),

('Select Bill Allocation','bill_allocation','select',null),
('Select Bank Transaction','bank_txn','select',null),
('Update Bank Transaction','bank_txn','update','{"bank_date"}'),

('Select Account Opening','account_opening','select',null),
('Set Account Opening','set_account_opening','execute',null),

('Select Inventory Opening','inventory_opening','select',null),
('Set Inventory Opening','set_inventory_opening','execute',null),

('Select Tds On Voucher','tds_on_voucher','select',null),
('Tds On Voucher Section Breakup','tds_on_voucher_section_break_up','execute',null),

('Select Exchange','exchange','select',null),
('Select Exchange Adjustment','exchange_adjustment','select',null),

('Select Voucher','voucher','select',null),
('Create Voucher','create_voucher','execute',null),
('Update Voucher','update_voucher','execute',null),
('Delete Voucher','delete_voucher','execute',null),
('Approve Voucher','approve_voucher','execute',null),

('Select Goods Inward Note','goods_inward_note','select',null),
('Create Goods Inward Note','create_goods_inward_note','execute',null),
('Update Goods Inward Note','update_goods_inward_note','execute',null),
('Delete Goods Inward Note','delete_goods_inward_note','execute',null),

('Select Gift Voucher','gift_voucher','select',null),
('Create Gift Voucher','create_gift_voucher','execute',null),
('Update Gift Voucher','update_gift_voucher','execute',null),
('Delete Gift Voucher','delete_gift_voucher','execute',null),

('Select Purchase Bill Inventory Item','purchase_bill_inv_item','select',null),
('Select Purchase Bill','purchase_bill','select',null),
('Create Purchase Bill','create_purchase_bill','execute',null),
('Update Purchase Bill','update_purchase_bill','execute',null),
('Delete Purchase Bill','delete_purchase_bill','execute',null),

('Select Debit Note Inventory Item','debit_note_inv_item','select',null),
('Select Debit Note','debit_note','select',null),
('Create Debit Note','create_debit_note','execute',null),
('Update Debit Note','update_debit_note','execute',null),
('Delete Debit Note','delete_debit_note','execute',null),

('Select Sale Bill Inventory Item','sale_bill_inv_item','select',null),
('Select Sale Bill','sale_bill','select',null),
('Create Sale Bill','create_sale_bill','execute',null),
('Update Sale Bill','update_sale_bill','execute',null),
('Delete Sale Bill','delete_sale_bill','execute',null),

('Select Credit Note Inventory Item','credit_note_inv_item','select',null),
('Select Credit Note','credit_note','select',null),
('Create Credit Note','create_credit_note','execute',null),
('Update Credit Note','update_credit_note','execute',null),
('Delete Credit Note','delete_credit_note','execute',null),

('Select Personal Use Purchase Inventory Item','personal_use_purchase_inv_item','select',null),
('Select Personal Use Purchase','personal_use_purchase','select',null),
('Create Personal Use Purchase','create_personal_use_purchase','execute',null),
('Update Personal Use Purchase','update_personal_use_purchase','execute',null),
('Delete Personal Use Purchase','delete_personal_use_purchase','execute',null),

('Select Stock Adjustment Inventory Item','stock_adjustment_inv_item','select',null),
('Select Stock Adjustment','stock_adjustment','select',null),
('Create Stock Adjustment','create_stock_adjustment','execute',null),
('Update Stock Adjustment','update_stock_adjustment','execute',null),
('Delete Stock Adjustment','delete_stock_adjustment','execute',null),

('Select Stock Deduction Inventory Item','stock_deduction_inv_item','select',null),
('Select Stock Deduction','stock_deduction','select',null),
('Create Stock Deduction','create_stock_deduction','execute',null),
('Update Stock Deduction','update_stock_deduction','execute',null),
('Delete Stock Deduction','delete_stock_deduction','execute',null),

('Select Stock Addition Inventory Item','stock_addition_inv_item','select',null),
('Select Stock Addition','stock_addition','select',null),
('Create Stock Addition','create_stock_addition','execute',null),
('Update Stock Addition','update_stock_addition','execute',null),
('Delete Stock Addition','delete_stock_addition','execute',null),

('Select Material Conversion Inventory Item','material_conversion_inv_item','select',null),
('Select Material Conversion','material_conversion','select',null),
('Create Material Conversion','create_material_conversion','execute',null),
('Update Material Conversion','update_material_conversion','execute',null),
('Delete Material Conversion','delete_material_conversion','execute',null),

('Select Customer Advance','customer_advance','select',null),
('Create Customer Advance','create_customer_advance','execute',null),
('Update Customer Advance','update_customer_advance','execute',null),
('Delete Customer Advance','delete_customer_advance','execute',null),

('Select Vendor Bill Map','vendor_bill_map','select',null),
('Insert Vendor Bill Map','vendor_bill_map','insert',null),
('Update Vendor Bill Map','vendor_bill_map','update','{"start_row", "name", "unit", "qty", "mrp", "rate", "free", "batch_no", "expiry",
    "expiry_format", "discount"}'),
('Delete Vendor Bill Map','vendor_bill_map','delete',null),

('Select Vendor Item Map','vendor_item_map','select',null),
('Insert Vendor Item Map','vendor_item_map','insert','{"vendor_id", "inventory_id", "vendor_inventory"}'),
('Update Vendor Item Map','vendor_item_map','update','{"vendor_inventory"}'),
('Delete Vendor Item Map','vendor_item_map','delete',null),

('Select Purchase Register Detail','purchase_register_detail','select',null),
('Select Sale Register Detail','sale_register_detail','select',null),
('Select Scheduled Drug Report','scheduled_drug_report','select',null),
('Select POS Counter Register','pos_counter_register','select',null),
('POS Counter Summary','pos_counter_summary','execute',null),

('Account Book Detail','account_book_detail','execute',null),
('Account Closing','account_closing','execute',null),
('Account Book Group','account_book_group','execute',null);
